botx/models/files.py
docs/changelog.md
pyproject.toml
tests/test_models/test_files/test_attributes.py

* has_supported_extension now supports uppercase extensions

has_supported_extension now supports uppercase extensions

---

botx/collecting/collectors/base.py
docs/changelog.md
pyproject.toml
tests/test_collecting/test_collector/test_collectors_merging/test_dependencies_order.py

Экзекутор для хендлера создается в `__post_init__` датакласса `Handler` в `botx/collecting/handlers/handler.py:78`
Сам датакласс `Handler` создается в `botx/collecting/collectors/base.py:BaseCollector:add_handler`
А зависимости, которые передаются в `include_collector` добавляются в `Handler` после инита в том же файле, функции `_add_handlers`.
Т.е. зависимости из `include_collector` не проходят `__post_init__` и соответственно не добавляются в экзекутор хендлера.
Для фикса я комбинирую зависимости в самом начале и передаю их в метод `add_handler`.

Fix dependencies in collector

---

botx/clients/clients/async_client.py
botx/clients/clients/sync_client.py
botx/exceptions.py
docs/changelog.md
pyproject.toml
tests/test_exceptions/test_route_deprecated_error.py

Raise BotXAPIRouteDeprecated exception when server returns http error 410 GONE.

raise special error on 410 GONE

---

botx/clients/methods/base.py
docs/changelog.md

The problem is parsing in json
There is a flag - exclude_none=True, therefore, when deleting a file, we have a payload.file=None and this field is simply thrown out of the request, and the server thinks that no action is required to be taken on the file and leaves it, if there is one

fix: File is now deleted when message is updated

---

botx/models/errors.py
docs/changelog.md
pyproject.toml
tests/test_models/test_errors.py

`BotDisabledErrorData.error_data` now can't be `Dict` and can only be `BotDisabledErrorData`

Fix BotDisabledResponse error_data validation

---

botx/bots/mixins/requests/files.py
docs/changelog.md
pyproject.toml
tests/test_bots/test_mixins/test_requests/test_files.py

Added `file_name` param to `download_file` method to provide ability to change returned file name

feat: add name param to `download_file` method

---

botx/bots/mixins/collecting/system_events.py
botx/collecting/collectors/mixins/system_events.py
botx/middlewares/ns.py
botx/models/enums.py
botx/models/events.py
botx/models/messages/incoming_message.py
botx/models/messages/message.py
botx/testing/building/entites.py
docs/changelog.md
pyproject.toml
tests/test_collecting/test_collector/test_decorators/test_system_event.py

Added `cts_login`  and `cts_logout` system events which are sent by botx when user joins or leaves corporate server.

feat: add `cts_login`  and `cts_logout` system events

---

tests/client/notifications_api/test_direct_notification.py

Fix `BotAccount` name error on `BotAccountWithSecret`

Fix name BotAccount to BotAccountWithSecret.

---

botx/models/status.py
tests/test_status.py

Fix validation in `BotApiStatusRecipient` class.
Now empty strings from query params given to the `BotApiStatusRecipient` processed correctly.
Example: `GET /status?ad_domain=&ad_login=&bot_id=uuid&chat_type=group_chat&is_admin=&user_huid=uuid`

Fix validation in BotApiStatusRecipient, now empty strings in query params processed correctly

---

botx/models/message/incoming_message.py
pyproject.toml
tests/test_attachments.py

- Fix crash bot if type attachment is not support.

fix: Add handling of unknown type attachment.

---

pybotx/models/attachments.py
pybotx/models/message/incoming_message.py
pybotx/models/stickers.py
pyproject.toml
tests/test_attachments.py

feature: Simplify attachments names, drop unnecessary field

---

pybotx/bot/bot.py
pybotx/client/openid_api/refresh_access_token.py
pyproject.toml
tests/client/openid_api/test_resfesh_access_token.py

Add refresh_access_token method

---

pybotx/__init__.py
pybotx/bot/bot.py
pybotx/client/events_api/delete_event.py
pybotx/client/exceptions/message.py
pyproject.toml
tests/client/events_api/test_delete_event.py

feat: delete message method

---

README.md
setup.cfg

docs: upgrade README.md

---

.github/dependabot.yml
.github/renovate.json

Этот PR включает Dependabot от Github, что позволяет следить за актуальностью зависимостей в репозитории.
Dependabot будет раз в неделю сканировать репозиторий и открывать/актуализировать PRы по обновлению той или иной зависимости.
Пример как это выглядит:
https://github.com/iteco-labss/pybotx/pull/5
Ранее в репозитории работал Renovate бот, который был отключен 20 января 2022 в этом коммите: e670feb5004ecd23a1bff663c5e6fe16c7e901a1
Файл конфига Renovate был удалён в данном PR.

feat(deps): включение Dependabot

---

pybotx/async_buffer.py
pybotx/bot/bot.py
pybotx/client/users_api/users_as_csv.py
pyproject.toml

fix: write bytes to csv file to avoid utf-8 decode error

---

pybotx/models/attachments.py
pyproject.toml
tests/test_attachments.py

fix: Change attachment voice extension

---

README.md
pybotx/bot/bot.py
pybotx/bot/bot_accounts_storage.py
pybotx/client/botx_method.py
pybotx/models/bot_account.py
pyproject.toml
tests/client/test_botx_method.py
tests/conftest.py
tests/models/test_bot_account.py
tests/test_end_to_end.py

fix: invalid issuer error during incoming request verification if the bot host contains url parts other than the domain

---

pybotx/models/message/forward.py
pybotx/models/message/incoming_message.py
tests/test_incoming_message.py

feat: data saturation for Forward entity

---

pybotx/client/users_api/user_from_csv.py
pybotx/models/users.py
pyproject.toml
tests/client/users_api/test_users_as_csv.py

feat: add 10 fields into UserFromCsv

---

pyproject.toml

docs: remove documentation link from toml

---

pybotx/__init__.py
pybotx/bot/bot.py
pybotx/client/smartapps_api/smartapp_manifest.py
pyproject.toml
tests/client/smartapps_api/test_smartapp_manifest.py

feat: subscribe to unread counter in sending manifest

---

pybotx/client/users_api/user_from_csv.py
pybotx/client/users_api/user_from_search.py
pybotx/models/users.py
pyproject.toml
tests/client/users_api/conftest.py
tests/client/users_api/test_users_as_csv.py

fix: in UserFromSearch field other_phone from int to str
