ExpressApp/pybotx

botx/collecting.py
botx/middlewares/ns.py
docs/changelog.md
tests/test_middlewares/test_ns.py

Refactor next step middleware:
* add background dependencies support
* use collector for storing handlers
* more strict behaviour

refactor ns middleware

---

botx/clients.py
botx/testing.py
docs/changelog.md

Encode update payload `by_alias`

fix update payload encoding

---

botx/__init__.py
docs/changelog.md
tests/conftest.py

Disalbe loguru logger as per [docs](https://loguru.readthedocs.io/en/stable/overview.html#suitable-for-scripts-and-libraries)

disable loguru logger

---

.github/workflows/styles.yml
.github/workflows/tests.yml
scripts/test

add codecov

---

botx/__init__.py
docs/src/development/tests/tests0/conftest.py
docs/src/development/tests/tests0/test_format_command.py
tests/conftest.py
tests/test_bots.py
tests/test_collectorts.py
tests/test_dependencies.py
tests/test_exception_handlers.py
tests/test_exceptions.py
tests/test_middlewares/test_exceptions.py
tests/test_middlewares/test_ns.py
tests/test_testing_client.py

* export `TestClient` and `MessageBuilder` from root namespace
* update tests for using updated imports and new fixture
* change docs

update using TestClient in tests and docs

---

botx/models/users.py
docs/changelog.md
pyproject.toml

Change param in UserInChatCreated model

Change name param to optional

---

botx/bots/mixins/requests/chats.py
botx/clients/methods/v3/chats/add_admin_role.py
botx/testing/botx_mock/asgi/application.py
botx/testing/botx_mock/asgi/routes/chats.py
botx/testing/botx_mock/wsgi/application.py
botx/testing/botx_mock/wsgi/routes/chats.py
botx/testing/typing.py
docs/changelog.md
docs/reference/clients/methods.md
pyproject.toml
tests/test_bots/test_mixins/test_requests/test_chats.py
tests/test_clients/test_methods/test_v3/test_chats/test_add_admin_role.py

Bot should have admin role itself to use it.

Add `bot.add_admin_roles` method

---

botx/models/buttons.py
botx/models/messages/sending/markup.py
botx/models/messages/sending/message.py
botx/models/messages/sending/payload.py
docs/changelog.md
pyproject.toml

Can be used in bubbles and keyboard buttons.

Add alerts (toast on button press)

---

botx/bots/bots.py
botx/bots/mixins/exceptions.py
botx/bots/mixins/lifespan.py
botx/bots/mixins/requests/call_protocol.py
botx/bots/mixins/requests/mixin.py
botx/bots/mixins/sending.py
botx/clients/clients/async_client.py
botx/clients/clients/sync_client.py
botx/clients/methods/base.py
botx/clients/types/message_payload.py
botx/collecting/collectors/mixins/default.py
botx/collecting/collectors/mixins/handler.py
botx/collecting/collectors/mixins/system_events.py
botx/models/typing.py
botx/shared.py
botx/typing.py
docs/changelog.md
pyproject.toml

Incoming messages logs already have it.

Add `bot_id` to outgoing messages debug logs

---

botx/bots/mixins/collecting/system_events.py
botx/collecting/collectors/mixins/system_events.py
botx/models/enums.py
botx/models/events.py
botx/models/messages/incoming_message.py
docs/changelog.md
pyproject.toml
tests/test_collecting/test_collector/test_decorators/test_system_event.py

This event stores deleted members HUIDs.

New event `deleted_from_chat`

---

botx/bots/mixins/sending.py
docs/changelog.md
tests/test_bots/test_mixins/test_requests/test_command.py
tests/test_bots/test_mixins/test_sending/test_answer_message.py
tests/test_bots/test_mixins/test_sending/test_send.py
tests/test_bots/test_mixins/test_sending/test_send_file.py
tests/test_bots/test_mixins/test_sending/test_send_message.py

* `send()` sending only direct notification, not command result

Use only direct notification via send()

---

botx/models/files.py
docs/changelog.md
pyproject.toml
tests/test_models/test_files/test_attributes.py

* New static method to check that file extension can be handled by BotX API

Add static method to check that file extension

---

botx/models/enums.py
botx/models/messages/incoming_message.py
botx/testing/building/builder.py
docs/changelog.md

Fields list:
* manufacturer (device brand)
* device (device name)
* device_software (device Operating System)
* device_meta (device metadata)
* platform (client platform name)
* platform_package_id (platform package ID with app data and device)
* app_version (Express app version)
* locale (session locale)

feature: Add new fields to message.user

---

botx/bots/mixins/requests/events.py
botx/bots/mixins/sending.py
botx/clients/types/message_payload.py
botx/models/messages/sending/payload.py
docs/changelog.md
pyproject.toml
tests/test_bots/test_mixins/test_requests/test_events.py
tests/test_bots/test_mixins/test_sending/test_answer_message.py

Add metadata to update methods and answer_message

Add metadata to update event and answer_message

---

botx/clients/methods/base.py
docs/changelog.md
pyproject.toml

Before file doesn't serialized when sending messages

fix: Serialize file

---

botx/bots/bots.py
botx/bots/mixins/lifespan.py
docs/changelog.md
pyproject.toml

fix: `bot.tasks` memory leak

---

.github/workflows/publish-pypi.yml

Auto publish to PyPi

---

botx/bots/mixins/requests/smartapps.py
botx/clients/methods/v3/smartapps/smartapp_event.py
botx/models/smartapps.py

Add async files for smartapp

---

poetry.lock
pyproject.toml

Remove FastAPI dep

---

botx/__init__.py
botx/bot/api/commands/bot_disabled_response.py
botx/bot/api/status/recipient.py
botx/bot/api/status/response.py
botx/bot/bot.py
botx/bot/handler.py
botx/bot/handler_collector.py
botx/bot/models/status/bot_menu.py
botx/bot/models/status/recipient.py
botx/typing.py
docs/reference/api/bot_api/responses/accepted.md
docs/reference/api/bot_api/responses/bot_disabled.md
docs/reference/bot/api/commands.md
mkdocs.yml
setup.cfg
tests/bot/api/status/test_status.py
tests/bot/test_bot_lifespan.py
tests/bot/test_handler_collector.py
tests/bot/test_incoming_message_routing.py
tests/bot/test_status.py

feat: Get bot status

---

botx/bot/bot.py
botx/bot/handler.py
botx/bot/handler_collector.py
botx/converters.py
poetry.lock
pyproject.toml
tests/bot/test_middlewares.py

Add middlewares

---

botx/bot/bot.py
botx/bot/middlewares/exceptions.py
poetry.lock
pyproject.toml
tests/bot/test_exception_middleware.py
tests/bot/test_middlewares.py

Add exception middleware

---

botx/bot/bot.py
botx/bot/middlewares/exceptions.py
tests/bot/test_exception_middleware.py

Change way to add exception handlers

---

botx/bot/bot.py
botx/client/botx_api_client.py
botx/client/chats_api/list_chats.py
setup.cfg
tests/client/bots_api/test_list_chats.py

Add list chats method

---

botx/bot/api/commands/base.py
botx/bot/api/commands/system_events/chat_created.py
botx/bot/api/status/recipient.py
botx/bot/bot.py
botx/client/bots_api/get_token.py
botx/client/botx_api_client.py
botx/client/botx_method.py
botx/client/chats_api/create_chat.py
botx/client/chats_api/list_chats.py
botx/client/missing.py
botx/client/notifications_api/direct_notification.py
botx/shared_models/api_base.py
tests/client/notifications_api/test_direct_notification.py
tests/client/test_botx_method.py
tests/test_end_to_end.py

feat: Add metadata to direct notification

---

botx/bot/api/commands/incoming_message.py
botx/bot/api/entities.py
botx/bot/api/enums.py
botx/bot/models/commands/entities.py
botx/bot/models/commands/enums.py
botx/bot/models/commands/incoming_message.py
setup.cfg
tests/bot/api/commands/test_files.py
tests/bot/api/commands/test_incoming_message.py
tests/client/chats_api/test_list_chats.py
tests/client/notifications_api/test_direct_notification.py
tests/conftest.py
tests/test_end_to_end.py

Add entities

---

botx/bot/api/commands/incoming_message.py
botx/bot/models/commands/incoming_message.py
botx/bot/models/commands/mentions.py
tests/bot/api/commands/test_incoming_message.py
tests/bot/models/commands/test_incoming_message.py
tests/bot/models/commands/test_mentions_list.py

Add mention collection

---

botx/__init__.py
botx/bot/bot.py
botx/client/notifications_api/direct_notification.py
botx/client/notifications_api/markup.py
botx/shared_models/api_base.py
setup.cfg
tests/client/notifications_api/test_direct_notification.py
tests/client/notifications_api/test_markup.py

feat: Now you can add buttons to message

---

botx/bots/mixins/requests/chats.py
botx/bots/mixins/requests/mixin.py
botx/clients/methods/errors/permissions.py
botx/clients/methods/v3/chats/pin_message.py
botx/clients/methods/v3/chats/unpin_message.py
botx/testing/botx_mock/asgi/application.py
botx/testing/botx_mock/asgi/routes/chats.py
botx/testing/botx_mock/wsgi/application.py
botx/testing/botx_mock/wsgi/routes/chats.py
docs/changelog.md
pyproject.toml
tests/test_bots/test_mixins/test_requests/test_chats.py
tests/test_clients/test_methods/test_errors/test_permissions.py
tests/test_clients/test_methods/test_v3/test_chats/test_pin_message.py
tests/test_clients/test_methods/test_v3/test_chats/test_unpin_message.py

feat: add pin and unpin methods

---

botx/bot/bot.py
botx/client/chats_api/disable_stealth.py
botx/client/chats_api/set_stealth.py
docs/botx_api.md
docs/reference/bot/bot.md
docs/reference/models.md
tests/client/chats_api/test_disable_stealth.py
tests/client/chats_api/test_set_stealth.py
tests/client/users_api/test_search_user_by_login.py

Add `enable_stealth` and `disable_stealth` methods

---

botx/__init__.py
botx/bot/bot.py
botx/client/chats_api/add_admin.py
botx/client/chats_api/exceptions.py
tests/client/chats_api/test_add_admin.py
tests/client/chats_api/test_remove_user.py

Add `promote_to_chat_admins` bot method

---

botx/bot/bot.py
botx/client/chats_api/pin_message.py
botx/client/chats_api/unpin_message.py
tests/client/chats_api/test_pin_message.py
tests/client/chats_api/test_unpin_message.py

Add `pin_message` and `unpin_message` bot methods

---

botx/__init__.py
botx/bots/mixins/collecting/system_events.py
botx/bots/mixins/requests/mixin.py
botx/bots/mixins/requests/smartapps.py
botx/clients/methods/v3/smartapps/__init__.py
botx/clients/methods/v3/smartapps/smartapp_event.py
botx/clients/methods/v3/smartapps/smartapp_notification.py
botx/collecting/collectors/mixins/system_events.py
botx/models/enums.py
botx/models/events.py
botx/models/messages/incoming_message.py
botx/models/messages/message.py
botx/models/smartapps.py
botx/testing/botx_mock/asgi/application.py
botx/testing/botx_mock/asgi/routes/chats.py
botx/testing/botx_mock/asgi/routes/smartapps.py
botx/testing/botx_mock/wsgi/application.py
botx/testing/botx_mock/wsgi/routes/chats.py
botx/testing/botx_mock/wsgi/routes/smartapps.py
docs/changelog.md
setup.cfg
tests/fixtures/smartapps.py
tests/test_bots/test_mixins/test_requests/test_smartapps.py
tests/test_clients/test_methods/test_base/test_empty_error_handlers.py
tests/test_clients/test_methods/test_v3/test_smartapps/test_smartapp_event.py
tests/test_clients/test_methods/test_v3/test_smartapps/test_smartapp_notification.py
tests/test_collecting/test_collector/test_decorators/test_system_event.py
tests/test_models/test_smartapps.py

Add smartapps

---

botx/client/botx_method.py
botx/client/chats_api/add_admin.py
botx/client/exceptions/base.py
tests/client/chats_api/test_add_admin.py
tests/client/test_botx_method.py
tests/client/test_botx_method_callback.py

Add possibility to add exception comment

---

botx/__init__.py
botx/bot/api/entities.py
botx/bot/api/enums.py
botx/bot/models/commands/entities.py
botx/bot/models/commands/enums.py
botx/client/notifications_api/direct_notification.py
botx/client/notifications_api/mentions.py
setup.cfg
tests/bot/api/commands/test_incoming_message.py
tests/bot/models/commands/test_mentions_list.py
tests/client/notifications_api/test_direct_notification.py
tests/test_end_to_end.py

Add embed mentions

---

botx/__init__.py
botx/bot/api/entities.py
setup.cfg
tests/bot/api/commands/test_attachments.py
tests/bot/api/commands/test_files.py
tests/bot/api/commands/test_incoming_message.py
tests/shared_models/test_attachments.py
tests/shared_models/test_files.py

Add possibility to get all mention

---

pyproject.toml

fix: Add mypy_extensions to required, move mkautodoc to dev

---

botx/bot/models/commands/mentions.py
tests/bot/models/commands/test_mentions_list.py

Add `.all_users_mentioned` property for `MentionList`.

feat: Add `.all_users_mentioned` property for `MentionList`

---

botx/bot/bot.py
botx/bot/bot_accounts_storage.py
tests/bot/api/commands/system_events/test_added_to_chat.py
tests/bot/api/commands/system_events/test_chat_created.py
tests/bot/api/commands/system_events/test_deleted_from_chat.py
tests/bot/api/commands/test_attachments.py
tests/bot/api/commands/test_files.py
tests/bot/api/commands/test_incoming_message.py
tests/bot/api/status/test_status.py
tests/bot/test_bot_lifespan.py
tests/bot/test_exception_middleware.py
tests/bot/test_incoming_message_routing.py
tests/bot/test_middlewares.py
tests/bot/test_state.py
tests/bot/test_system_events_routing.py
tests/conftest.py
tests/test_end_to_end.py

fix: check bot account by bot_id when message is recieved

---

botx/bot/api/commands/base.py
botx/bot/api/commands/incoming_message.py
botx/bot/api/commands/system_events/added_to_chat.py
botx/bot/api/commands/system_events/chat_created.py
botx/bot/api/commands/system_events/deleted_from_chat.py
botx/bot/models/commands/incoming_message.py

refactor: Move sender validation to contexts

---

botx/__init__.py
botx/bot/bot.py
botx/client/notifications_api/direct_notification.py
botx/client/notifications_api/exceptions.py
tests/client/notifications_api/test_direct_notification.py
tests/client/notifications_api/test_markup.py
tests/test_end_to_end.py

Move direct notification to v4

---

botx/bot/api/status/recipient.py
botx/bot/models/status/recipient.py
tests/bot/api/commands/system_events/test_added_to_chat.py
tests/bot/api/commands/system_events/test_chat_created.py
tests/bot/api/commands/system_events/test_deleted_from_chat.py
tests/bot/api/commands/test_attachments.py
tests/bot/api/commands/test_files.py
tests/bot/api/commands/test_incoming_message.py
tests/bot/models/test_status_recipient.py
tests/bot/test_bot_lifespan.py
tests/bot/test_exception_middleware.py
tests/bot/test_incoming_message_routing.py
tests/bot/test_middlewares.py
tests/bot/test_state.py
tests/bot/test_system_events_routing.py

Add `from_incoming_message` method to `StatusRecipient`.

feat: from incoming message method

---

tests/bot/api/commands/system_events/test_added_to_chat.py
tests/bot/api/commands/system_events/test_chat_created.py
tests/bot/api/commands/system_events/test_deleted_from_chat.py
tests/bot/api/commands/test_attachments.py
tests/bot/api/commands/test_files.py
tests/bot/api/commands/test_incoming_message.py
tests/bot/test_bot_lifespan.py
tests/bot/test_exception_middleware.py
tests/bot/test_incoming_message_routing.py
tests/bot/test_middlewares.py
tests/bot/test_state.py
tests/bot/test_system_events_routing.py
tests/client/notifications_api/test_direct_notification.py

fix: add mock for bot auth

---

botx/bot/api/commands/incoming_message.py
botx/bot/api/entities.py
botx/bot/models/commands/entities.py
botx/bot/models/commands/incoming_message.py
tests/bot/api/commands/test_incoming_message.py
tests/bot/models/commands/test_mentions_list.py

Add mentions in reply

---

botx/bot/bot.py
botx/bot/callbacks_manager.py
botx/bot/handler_collector.py
botx/bot/middlewares/exceptions.py
botx/client/botx_method.py
botx/logger.py
botx/shared_models/api_base.py
poetry.lock
setup.cfg
tests/conftest.py
tests/shared_models/test_files.py
tests/test_end_to_end.py

feat: Add basic logging

---

botx/bot/models/commands/incoming_message.py
tests/bot/models/commands/test_incoming_message.py

Added `argument` & `arguments` property for incoming message

Add argument & arguments property for incoming message

---

botx/bot/bot.py
botx/client/notifications_api/direct_notification.py
botx/models/api_base.py
tests/client/notifications_api/test_direct_notification.py
tests/client/notifications_api/test_markup.py

Add button_auto_adjust option

---

botx/bot/bot.py
botx/client/chats_api/create_chat.py
botx/client/chats_api/set_stealth.py
tests/client/chats_api/test_create_chat.py
tests/client/chats_api/test_set_stealth.py

Make `enable_stealth` options `Undefined` by default

---

botx/models/base_command.py
botx/models/message/incoming_message.py
tests/test_incoming_message.py

fix: device meta field

---

botx/bot/bot.py
tests/test_handler_collector.py

Fix unclosed AsyncClient tests warning

---

botx/__init__.py
botx/bot/exceptions.py
botx/bot/handler_collector.py
tests/test_handler_collector.py
tests/test_lifespan.py

fix: Log "handler not found" instead of unnecessary raise

---

botx/models/base_command.py
botx/models/chats.py
botx/models/message/incoming_message.py
botx/models/system_events/added_to_chat.py
botx/models/system_events/chat_created.py
botx/models/system_events/deleted_from_chat.py
tests/conftest.py
tests/system_events/test_added_to_chat.py
tests/system_events/test_chat_created.py
tests/system_events/test_deleted_from_chat.py
tests/test_incoming_message.py

Move chat attribute from Chat to BotCommandBase

---

botx/__init__.py
botx/bot/handler.py
botx/bot/handler_collector.py
botx/models/commands.py
botx/models/system_events/left_from_chat.py
tests/system_events/test_left_from_chat.py

Add `left_from_chat` event

---

botx/bot/bot.py
botx/client/smartapps_api/smartapp_event.py
botx/constants.py
botx/models/async_files.py
botx/models/enums.py
setup.cfg
tests/client/smartapps_api/test_smartapp_event.py
tests/test_files.py
tests/test_incoming_message.py

Add `Bot.send_smartapp_event` method

---

botx/bot/bot.py
botx/client/events_api/edit_event.py
tests/client/events_api/test_edit_event.py

feat: Add method to edit message

---

botx/__init__.py
botx/bot/handler.py
botx/bot/handler_collector.py
botx/models/commands.py
botx/models/system_events/cts_login.py
botx/models/system_events/cts_logout.py
tests/system_events/test_cts_login.py
tests/system_events/test_cts_logout.py

Added `cts_login` and `cts_logout` events.

Add `cts_login` and `cts_logout` events

---

botx/__init__.py
botx/bot/handler.py
botx/bot/handler_collector.py
botx/models/base_command.py
botx/models/chats.py
botx/models/commands.py
botx/models/message/incoming_message.py
botx/models/system_events/added_to_chat.py
botx/models/system_events/chat_created.py
botx/models/system_events/deleted_from_chat.py
botx/models/system_events/left_from_chat.py
tests/conftest.py
tests/system_events/test_added_to_chat.py
tests/system_events/test_chat_created.py
tests/system_events/test_deleted_from_chat.py
tests/system_events/test_left_from_chat.py
tests/test_incoming_message.py

[fix push] Left from chat event

---

botx/bot/bot.py
botx/client/smartapps_api/smartapp_event.py
botx/constants.py
botx/models/async_files.py
botx/models/base_command.py
botx/models/chats.py
botx/models/enums.py
botx/models/message/incoming_message.py
botx/models/system_events/added_to_chat.py
botx/models/system_events/chat_created.py
botx/models/system_events/deleted_from_chat.py
setup.cfg
tests/client/smartapps_api/test_smartapp_event.py
tests/conftest.py
tests/system_events/test_added_to_chat.py
tests/system_events/test_chat_created.py
tests/system_events/test_deleted_from_chat.py
tests/test_files.py
tests/test_incoming_message.py

[fix push] Send smartapp event

---

botx/__init__.py
botx/bot/handler.py
botx/bot/handler_collector.py
botx/models/commands.py
botx/models/system_events/cts_login.py
botx/models/system_events/cts_logout.py
tests/system_events/test_cts_login.py
tests/system_events/test_cts_logout.py

[fix push] Cts events

---

botx/bot/bot.py
botx/client/events_api/edit_event.py
tests/client/events_api/test_edit_event.py

[fix push] Edit message

---

botx/__init__.py
botx/models/message/incoming_message.py
tests/conftest.py
tests/test_incoming_message.py

Merge app and device contexts

---

botx/client/chats_api/add_admin.py
botx/client/chats_api/add_user.py
botx/client/chats_api/disable_stealth.py
botx/client/chats_api/pin_message.py
botx/client/chats_api/remove_user.py
botx/client/chats_api/set_stealth.py
botx/client/chats_api/unpin_message.py
botx/client/smartapps_api/smartapp_event.py
botx/models/system_events/added_to_chat.py
botx/models/system_events/chat_created.py

Remove unnessesary validation

---

tests/client/chats_api/test_add_admin.py
tests/client/chats_api/test_add_user.py
tests/client/chats_api/test_chat_info.py
tests/client/chats_api/test_create_chat.py
tests/client/chats_api/test_disable_stealth.py
tests/client/chats_api/test_pin_message.py
tests/client/chats_api/test_remove_user.py
tests/client/chats_api/test_set_stealth.py
tests/client/chats_api/test_unpin_message.py
tests/client/files_api/test_download_file.py
tests/client/files_api/test_upload_file.py
tests/client/notifications_api/test_direct_notification.py
tests/client/notifications_api/test_internal_bot_notification.py
tests/client/notifications_api/test_markup.py
tests/client/smartapps_api/test_smartapp_event.py
tests/client/test_authorized_botx_method.py
tests/client/test_botx_method.py
tests/client/test_botx_method_callback.py
tests/client/users_api/test_search_user_by_huid.py
tests/conftest.py
tests/test_attachments.py
tests/test_callback.py
tests/test_files.py
tests/test_system_events_routing.py

Refactor fixtures

---

botx/bot/bot.py
tests/client/bots_api/test_get_token.py
tests/client/chats_api/test_add_admin.py
tests/client/chats_api/test_add_user.py
tests/client/chats_api/test_chat_info.py
tests/client/chats_api/test_create_chat.py
tests/client/chats_api/test_disable_stealth.py
tests/client/chats_api/test_list_chats.py
tests/client/chats_api/test_pin_message.py
tests/client/chats_api/test_remove_user.py
tests/client/chats_api/test_set_stealth.py
tests/client/chats_api/test_unpin_message.py
tests/client/files_api/test_download_file.py
tests/client/files_api/test_upload_file.py
tests/client/notifications_api/test_direct_notification.py
tests/client/notifications_api/test_markup.py
tests/client/users_api/test_search_user_by_email.py
tests/client/users_api/test_search_user_by_huid.py
tests/client/users_api/test_search_user_by_login.py

Make client args kwonly

---

botx/__init__.py
botx/bot/bot.py
botx/bot/handler_collector.py
botx/models/base_command.py
botx/models/bot_recipient.py
botx/models/message/incoming_message.py
botx/models/status.py
botx/models/system_events/added_to_chat.py
botx/models/system_events/chat_created.py
botx/models/system_events/cts_login.py
botx/models/system_events/cts_logout.py
botx/models/system_events/deleted_from_chat.py
botx/models/system_events/left_from_chat.py
tests/conftest.py
tests/models/test_status_recipient.py
tests/system_events/test_added_to_chat.py
tests/system_events/test_chat_created.py
tests/system_events/test_cts_login.py
tests/system_events/test_cts_logout.py
tests/system_events/test_deleted_from_chat.py
tests/system_events/test_left_from_chat.py
tests/test_incoming_message.py
tests/test_system_events_routing.py

Bot recipient

---

scripts/lint
scripts/wip_marks

Linter for wip marks

---

botx/bot/bot.py
botx/client/notifications_api/direct_notification.py
tests/client/notifications_api/test_direct_notification.py

Add recipients arg to direct notification

---

botx/__init__.py
botx/bot/bot.py
botx/models/message/outgoing_message.py
docs/botx_api.md
tests/client/notifications_api/test_direct_notification.py
tests/client/notifications_api/test_markup.py
tests/test_end_to_end.py

Add OutgoingMessage

---

botx/__init__.py
botx/bot/handler.py
botx/bot/handler_collector.py
botx/models/bot_sender.py
botx/models/commands.py
botx/models/system_events/internal_bot_notification.py
tests/system_events/test_internal_bot_notification.py

Add support of `internal_bot_notification` event

Add `internal_bot_notification` event

---

botx/bot/bot.py
botx/client/events_api/reply_event.py
tests/client/events_api/test_reply_event.py

feat: Add reply method

---

botx/bot/bot.py
botx/client/notifications_api/direct_notification.py
botx/models/message/outgoing_message.py
tests/client/notifications_api/test_direct_notification.py

Add silent_response to direct-notification

---

botx/bot/bot.py
botx/client/smartapps_api/smartapp_notification.py
tests/client/smartapps_api/test_smartapp_notification.py

Add smartapp notification method

Add smartapp notification method

---

botx/models/stickers.py
tests/test_stickers.py

Add sticker download method

---

botx/bot/bot.py
botx/client/stickers_api/delete_sticker.py
tests/client/stickers_api/test_delete_sticker.py

Add delete sticker from sticker pack method

Add delete sticker from sticker pack method

---

botx/__init__.py
botx/bot/handler.py
botx/bot/handler_collector.py
botx/models/commands.py
botx/models/system_events/smartapp.py
tests/system_events/test_smartapp.py

Add smartapp event

---

tests/client/test_botx_method_callback.py
tests/test_handler_collector.py
tests/test_lifespan.py

Remove unnecessary sleeps in tests

---

botx/bot/bot.py
botx/models/api_base.py
setup.cfg
tests/client/smartapps_api/test_smartapp_event.py
tests/client/test_botx_method.py
tests/client/test_botx_method_undefined_cleaned.py
tests/models/test_mentions_list.py
tests/test_handler_collector.py
tests/test_lifespan.py

Fix full coverage

---

botx/bot/bot.py
botx/client/stickers_api/create_sticker_pack.py
botx/client/stickers_api/get_sticker_pack.py
botx/models/stickers.py
tests/client/stickers_api/test_create_sticker_pack.py
tests/client/stickers_api/test_get_sticker_pack.py

feat: Add get sticker pack method

---

.github/workflows/python_app.yml

chore: Update python versions in CI matrix

---

botx/__init__.py
botx/bot/bot.py
botx/client/stickers_api/add_sticker.py
botx/client/stickers_api/exceptions.py
botx/client/stickers_api/get_sticker.py
botx/client/stickers_api/get_sticker_pack.py
tests/client/stickers_api/test_add_sticker.py
tests/client/stickers_api/test_get_sticker.py
tests/client/stickers_api/test_get_sticker_pack.py

feat: Add get sticker method

---

botx/bot/bot.py
botx/bot/handler_collector.py

change: Bot refactoring

---

botx/bot/handler_collector.py
tests/test_end_to_end.py
tests/test_middlewares.py

Add middleware in default handler.

fix: Add middleware in default handler

---

botx/__init__.py
botx/bot/bot.py
botx/models/message/edit_message.py
tests/client/events_api/test_edit_event.py

Add Bot.edit method

---

botx/client/chats_api/chat_info.py
botx/models/enums.py
botx/models/message/incoming_message.py
botx/models/system_events/chat_created.py

Uniform method naming

---

botx/bot/bot.py
botx/client/stickers_api/edit_sticker_pack.py
botx/client/stickers_api/get_sticker_pack.py
botx/client/stickers_api/sticker_pack.py
botx/client/stickers_api/sticker_pack_search.py
tests/client/stickers_api/test_edit_sticker_pack.py

Add method for editing a set of stickers.

feat: Add edit sticker pack method.

---

botx/bot/bot.py

Replace positional args to kwargs

---

botx/bot/bot.py
botx/client/stickers_api/delete_sticker.py
botx/client/stickers_api/delete_sticker_pack.py
tests/client/stickers_api/test_delete_sticker.py
tests/client/stickers_api/test_delete_sticker_pack.py

Add delete sticker pack method

Add delete sticker pack method

---

botx/bot/bot.py
botx/client/events_api/typing_event.py
tests/client/events_api/test_typing_event.py

Add support of `typing` event

---

botx/bot/bot.py
botx/client/events_api/stop_typing_event.py
tests/client/events_api/test_stop_typing_event.py

Add support `stop_typing` event

Add support `stop_typing` event

---

botx/models/system_events/smartapp_event.py
tests/system_events/test_smartapp_event.py

Add sender for smartapp event.

Add forwarding sending smartapp event response payload.

---

botx/__init__.py
botx/bot/bot.py
botx/client/events_api/message_status_event.py
botx/client/exceptions/event.py
botx/models/message/message_status.py
tests/client/events_api/test_message_status_event.py

Add message status event

---

botx/__init__.py
botx/bot/bot.py
botx/models/message/reply_message.py
tests/client/events_api/test_reply_event.py

Add method reply message event.

Add reply message event.

---

botx/bot/handler_collector.py
tests/test_handler_collector.py

Add `HandlerCollector.handle_incoming_message` method

---

botx/bot/bot.py
tests/client/test_botx_method_callback.py

feat: add `wait_botx_method_callback` method to bot

---

botx/__init__.py
botx/logger.py
tests/conftest.py

fix: Using loguru best practices

---

botx/bot/bot.py

fix: BotX command logs

---

pybotx/__init__.py
pybotx/models/enums.py
pybotx/models/message/incoming_message.py
pybotx/models/message/mentions.py
pyproject.toml
tests/client/events_api/test_edit_event.py
tests/client/events_api/test_reply_event.py
tests/client/notifications_api/test_direct_notification.py
tests/models/test_mentions_list.py
tests/test_incoming_message.py

fix: Types mentions.

---

pybotx/bot/callbacks_manager.py
pyproject.toml

fix: Log for callback, which wasn't waited

---

README.md

docs: Change README language

---

pybotx/models/message/mentions.py
pyproject.toml

fix: MentionList return types.

---

README.md
scripts/docs-lint
setup.cfg

feat: Add code examples to README

---

poetry.lock
pyproject.toml
tests/test_end_to_end.py

Remove read credentials from env

---

tests/conftest.py

Add fixture respx_mocking

---

README.md
pybotx/client/events_api/edit_event.py
pybotx/client/events_api/reply_event.py
pybotx/client/notifications_api/direct_notification.py
pybotx/models/message/incoming_message.py
pyproject.toml
tests/test_files.py
tests/test_incoming_message.py

Remove async-files from IncomingMessage

---

pybotx/client/exceptions/callbacks.py
pybotx/client/exceptions/http.py

chore: Remove extra comments

---

pybotx/bot/bot.py
pyproject.toml
tests/test_lifespan.py

feat: Possibility to skip fetching tokens on startup

---

poetry.lock
pyproject.toml

chore: Bump httpx version to 0.23.0.

---

pybotx/client/chats_api/list_chats.py
pyproject.toml
tests/client/chats_api/test_list_chats.py

Processing of unsupported chat types

---

pybotx/client/chats_api/list_chats.py

chore: replace list comprehension with generator

---

pybotx/bot/bot.py
pybotx/client/users_api/search_user_by_other_id.py
pybotx/client/users_api/user_from_search.py
pybotx/models/users.py
pyproject.toml
tests/client/users_api/test_search_user_by_email.py
tests/client/users_api/test_search_user_by_huid.py
tests/client/users_api/test_search_user_by_other_id.py

Search for a user by other_id

---

pybotx/bot/bot.py
tests/client/users_api/test_search_user_by_other_id.py

fix: method name

---

pybotx/client/chats_api/chat_info.py
pybotx/client/chats_api/list_chats.py
pybotx/models/chats.py
pyproject.toml
tests/client/chats_api/test_chat_info.py
tests/client/chats_api/test_list_chats.py

feat: Add share_history field to Chats API

---

pybotx/client/chats_api/chat_info.py
pybotx/models/enums.py
pyproject.toml
tests/client/chats_api/test_chat_info.py

Extend user types

---

pybotx/client/users_api/user_from_search.py
pybotx/models/users.py
pyproject.toml
tests/client/users_api/test_search_user_by_email.py
tests/client/users_api/test_search_user_by_huid.py
tests/client/users_api/test_search_user_by_login.py
tests/client/users_api/test_search_user_by_other_id.py

feat: Add user_kind field to Users API

---

.github/workflows/python-app.yml
README.md
poetry.lock
pybotx/async_buffer.py
pybotx/bot/bot.py
pybotx/client/exceptions/users.py
pybotx/client/users_api/user_from_csv.py
pybotx/client/users_api/users_as_csv.py
pybotx/models/enums.py
pybotx/models/users.py
pyproject.toml
tests/client/users_api/test_users_as_csv.py

feat: Method for getting a list of users on a CTS

---

poetry.lock
pyproject.toml

chore: Update upper pydantic version to 1.11.0

---

pybotx/client/chats_api/create_chat.py
pybotx/client/chats_api/list_chats.py
pybotx/models/api_base.py
pybotx/models/base_command.py
pybotx/models/chats.py
pybotx/models/enums.py
pybotx/models/status.py
pyproject.toml
tests/client/chats_api/test_create_chat.py
tests/test_incoming_message.py

refactor: Update UNSUPPORTED chat type implementation

---

pybotx/__init__.py

feat: Import model types directly from pybotx

---

pyproject.toml

chore: Bump the project version

---

pybotx/client/users_api/user_from_csv.py
pybotx/models/enums.py
pybotx/models/users.py
pyproject.toml
tests/client/users_api/test_users_as_csv.py

refactor: Proccessing of unsupported sync source types

---

pybotx/client/stickers_api/get_sticker_packs.py
pyproject.toml

fix: get first page of sticker packs

---

pybotx/bot/bot.py
pybotx/client/users_api/search_user_by_emails.py
pybotx/client/users_api/user_from_search.py
pyproject.toml
tests/client/users_api/test_search_user_by_emails.py

feat: method for search user by emails

---

pybotx/bot/bot.py
pybotx/client/smartapps_api/smartapp_custom_notification.py
pyproject.toml
setup.cfg
tests/client/smartapps_api/test_smartapp_custom_notification.py

feat: /api/v4/botx/smartapps/notification support

---

pybotx/client/smartapps_api/smartapp_custom_notification.py
pyproject.toml
tests/client/smartapps_api/test_smartapp_custom_notification.py

fix: Custom push fields

---

poetry.lock
pyproject.toml

Bump httpx

---

pybotx/client/botx_method.py
pyproject.toml

feat: added URL path support for bots' hosts

---

pybotx/__init__.py
pybotx/bot/handler.py
pybotx/bot/handler_collector.py
pybotx/models/commands.py
pybotx/models/enums.py
pybotx/models/system_events/event_edit.py
pyproject.toml
tests/system_events/test_event_edit.py

feat: Add edit system event

---

pybotx/models/system_events/event_edit.py
pyproject.toml
tests/system_events/test_event_edit.py

fix: Add attachments and entities in system event edit

---

pybotx/bot/bot.py
pyproject.toml
tests/test_base_command.py

feat: added logging flag for incoming requests data

---

.github/workflows/python-app.yml
pyproject.toml

chore: add support python 3.12

---

pybotx/client/botx_method.py
pyproject.toml
tests/client/test_botx_method.py

feat: Add protocols support in url builder

---

.github/workflows/python-app.yml
pybotx/bot/bot.py

fix: unverified request due to invalid iat

---

pybotx/__init__.py
pybotx/bot/bot.py
pybotx/client/smartapps_api/smartapp_manifest.py
pybotx/models/enums.py
tests/client/smartapps_api/test_smartapp_manifest.py

feat: add send_smartapp_manifest method

---

pyproject.toml

chore: bump project version from 0.65.0 to 0.66.0

---

poetry.lock
pyproject.toml

fix: return mypy-extensions to main deps

---

pyproject.toml

chore: bump project version

---

pybotx/bot/bot.py
pybotx/client/smartapps_api/smartapp_unread_counter.py
pyproject.toml
tests/client/smartapps_api/test_smartapp_unread_counter.py

feat: /api/v4/botx/smartapps/unread_counter support

---

pybotx/__init__.py
pybotx/client/smartapps_api/smartapp_manifest.py
pybotx/models/enums.py
pyproject.toml

feat: aurora support
